// <auto-generated />
namespace DataAcessesLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class add_ImagePath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ImagePath));
        
        string IMigrationMetadata.Id
        {
            get { return "202203141514309_add_ImagePath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
